from dash import html, dcc, dash_table
import dash_bootstrap_components as dbc

from gera_base import carrega_bases
df, df_agenda, df_consulta, nomes, colaboradores = carrega_bases()

layout_consulta_setting_analitico = html.Div([
    html.Div([dbc.Accordion([
        dbc.AccordionItem([
            html.H6('Primeira Consulta:'),
            html.Small('O que te levou a procurar terapia nesse momento?', style={'display': 'block'}),
            html.Small('Você já realizou algum tipo de terapia antes? Como foi a experiência?', style={'display': 'block'}),
            html.Small('O que você está sentindo neste momento?', style={'display': 'block'}),
            html.Small('O que você gostaria que mudasse quando sair daqui hoje?', style={'display': 'block'}),
            html.Small('Como eu poderia te ajudar hoje?', style={'display': 'block'}),
            html.Small('O que você gostaria que acontecesse hoje para tornar esta sessão útil?', style={'display': 'block'}),
            html.Small('Qual sua expectativa para nossas sessões de terapia?', style={'display': 'block'}),
            html.Small('O que te impactou negativamente esta semana?', style={'display': 'block'}),
            html.Small('O que você gostaria de realizar na terapia?', style={'display': 'block'}),
            html.Small('Qual é a sua maior/principal preocupação hoje?', style={'display': 'block'}),
            html.Small('De quem foi a ideia de você estar aqui hoje buscando ajuda?', style={'display': 'block'}),
            html.Small('O que tem dado muito certo na sua vida até o momento?', style={'display': 'block'}),
            html.P(),
            html.H6('Paciente Recorrente:'),
            html.Small('O que mudou hoje, comparado a última vez que você esteve aqui?', style={'display': 'block'}),
            html.Small('Você acredita que tem algo de errado com a sua vida? O que?', style={'display': 'block'}),
            html.Small('No que você está pensando nesse momento?', style={'display': 'block'}),
            html.Small('No que você estava pensando antes de entrar nessa sala?', style={'display': 'block'}),
            html.Small('Em todo esse período após o nosso último encontro até hoje, o que você fez que foi mais útil ?', style={'display': 'block'}),
            html.Small('Como você conseguiu levantar da cama e vir até aqui hoje?', style={'display': 'block'}),
            html.Small('Qual o seu nível de expectativa/engajamento para continuar em terapia?', style={'display': 'block'}),
        ], title='Início de Sessão'),
        dbc.AccordionItem([
            html.Small('O que você definiria como o seu maior problema hoje?', style={'display': 'block'}),
            html.Small('Como você enxerga o problema?', style={'display': 'block'}),
            html.Small('O que esse problema(s) causou na sua vida?', style={'display': 'block'}),
            html.Small('Qual você acha que é o problema no seu ponto de vista?', style={'display': 'block'}),
            html.Small('Você se sente o causador dos problemas? Sente algum grau de culpa?', style={'display': 'block'}),
            html.Small('O que você já tentou até agora para resolver seu problema?', style={'display': 'block'}),
            html.Small('Como você acha que vai melhorar ou resolver esse problema?', style={'display': 'block'}),
            html.Small('Como você definiria o maior desafio que está enfrentando no momento?', style={'display': 'block'}),
            html.Small('Como você definiria o maior desafio que está enfrentando no momento?', style={'display': 'block'}),
            html.Small('Você fez algo no passado que funcionou bem para resolver este mesmo tipo de problema?', style={'display': 'block'}),
            html.Small('Qual a sensação que esse problema te trás? Como você se sente com ele?', style={'display': 'block'}),
            html.Small('Quais são as coisas, pessoas ou situações em sua vida que estão causando problemas para você?', style={'display': 'block'}),
            html.Small('Você sofre com esse problema todos os dias?', style={'display': 'block'}),
            html.Small('O que você tem feito para lidar com o(s) problema(s) que o trouxe para a terapia?', style={'display': 'block'}),
            html.Small('Você aceitaria minhas sugestões de como contornar / resolver seus problemas?', style={'display': 'block'}),
            html.Small('O que você acha que fez com que a situação piorasse?', style={'display': 'block'}),
            html.Small('Como o problema afeta como você se sente sobre si mesmo?', style={'display': 'block'}),
            html.Small('Você se sente triste, louco, sem esperança, preso ou outra coisa parecia?', style={'display': 'block'}),
            html.Small('Conte-me sobre quando você não estava passando por esses problemas ou dificuldades.', style={'display': 'block'}),
            html.Small('O que você poderia fazer diferente hoje para conseguir um resultado melhor na resolução desse problema?', style={'display': 'block'}),
            html.Small('Se as coisas melhoraram, concentre-se nos detalhes de como o cliente fez isso acontecer (pontos fortes e resiliências)', style={'display': 'block'}),
            html.Small('Como você conseguiu dar um passo tão grande?', style={'display': 'block'}),
            html.Small('O que você disse a si mesmo que o incentivou / encorajou a agir dessa maneira?', style={'display': 'block'}),
            html.Small('O que você pretende fazer para manter esse resultado?', style={'display': 'block'}),
            html.P(),
        ], title='Problemática'),
        dbc.AccordionItem([
            html.Small('Com que frequência você se encontra com os amigos?', style={'display': 'block'}),
            html.Small('Você e seu parceiro têm uma boa relação de conversa juntos?', style={'display': 'block'}),
            html.Small('Como está o seu sono esses dias? Está dormindo bem?', style={'display': 'block'}),
            html.Small('Você está feliz com a sua alimentação?', style={'display': 'block'}),
            html.Small('Você tem praticado alguma atividade física?', style={'display': 'block'}),
            html.Small('Existe alguém que você sente que realmente te entende?', style={'display': 'block'}),
            html.Small('Existe alguém que você sente que realmente te entende?', style={'display': 'block'}),
            html.Small('Que escolha você tem sobre o que acontece em sua vida?', style={'display': 'block'}),
            html.Small('Você tem uma noção clara de onde você quer chegar na vida?', style={'display': 'block'}),
            html.Small('Você se sente animado pelas coisas que acontecem em sua vida?', style={'display': 'block'}),
            html.Small('Que envolvimento você tem com as pessoas ao seu redor?', style={'display': 'block'}),
            html.Small('Você sente que tem um propósito?', style={'display': 'block'}),
            html.Small('Você se sente seguro em casa?', style={'display': 'block'}),
            html.Small('Quais necessidades você sente que não são atendidas?', style={'display': 'block'}),
        ], title='Necessidades'),
        dbc.AccordionItem([
            html.H6('Avaliação de Ideação Suicida:'),
            html.Small('Às vezes as pessoas sentem que a vida não vale a pena ser vivida. Você pode me dizer como você se sente sobre sua própria vida?', style={'display': 'block'}),
            html.Small('Quais são alguns dos aspectos da sua vida que fazem valer a pena viver?', style={'display': 'block'}),
            html.Small('Quais são alguns dos aspectos de sua vida que podem fazer você sentir ou pensar que sua vida não vale a pena?', style={'display': 'block'}),
            html.Small('Você se encontra desejando uma fuga permanente da vida?', style={'display': 'block'}),
            html.Small('Como isso aconteceria com você?', style={'display': 'block'}),
            html.Small('Você pensa em sua própria morte ou em morrer?', style={'display': 'block'}),
            html.Small('Você já pensou em se machucar ou tentar tirar a própria vida?', style={'display': 'block'}),
            html.Small('Você pensa ou se sente assim atualmente?', style={'display': 'block'}),
            html.P(),
            html.P('Se é identificável a permanência de pensamentos suicidas:'),
            html.Small('Quando você começou a ter esses pensamentos e sentimentos?', style={'display': 'block'}),
            html.Small('O que aconteceu antes que causou esses pensamentos?', style={'display': 'block'}),
            html.Small('Houve eventos em sua vida que precederam isso, como uma perda repentina ou sentimentos de depressão?', style={'display': 'block'}),
            html.Small('Com que frequência você teve esses pensamentos e sentimentos?', style={'display': 'block'}),
            html.Small('Quão fortes são esses pensamentos?', style={'display': 'block'}),
            html.Small('Você pode descrevê-los?', style={'display': 'block'}),
            html.Small('Você já agiu de acordo com o que esses pensamentos mandam?', style={'display': 'block'}),
            html.Small('Se você não agiu de acordo com eles, quão perto você sente que chegou de atuar?', style={'display': 'block'}),
            html.Small('O que o impediu de atuar neles?', style={'display': 'block'}),
            html.Small('Você já começou a agir de acordo com seus pensamentos suicidas ou de automutilação, mas parou antes de fazê-lo?', style={'display': 'block'}),
            html.Small('Você acha que pode agir de acordo com esses pensamentos de automutilação ou suicídio no futuro?', style={'display': 'block'}),
            html.Small('Se você tirasse sua própria vida, o que você imagina que aconteceria depois que você morresse para aquelas pessoas que são importantes para você?', style={'display': 'block'}),
            html.Small('Você tem um plano para se machucar ou tirar sua própria vida? Se sim, descreva seu plano.', style={'display': 'block'}),
            html.Small('Você tem esses métodos disponíveis para tirar sua vida, como pílulas venenosas, facas ou proximidade de uma varanda ou ponte?', style={'display': 'block'}),
            html.Small('Você se preparou para sua morte escrevendo um bilhete, fazendo um testamento, praticando o plano, colocando seu assuntos como suas finanças em ordem, ou garantindo a privacidade de tal forma que você dificilmente seria descoberto?', style={'display': 'block'}),
            html.Small('Você já disse a alguém que está pensando em tirar sua vida ou está planejando fazer isso?', style={'display': 'block'}),
            html.P(),
            html.P('Se o paciente já tentou suicídio ou automutilação:'),
            html.Small('Você já disse a alguém que está pensando em tirar sua vida ou está planejando fazer isso?', style={'display': 'block'}),
            html.Small('O que levou a isso?', style={'display': 'block'}),
            html.Small('Você estava usando álcool ou outras substâncias?', style={'display': 'block'}),
            html.Small('Qual método você usou?', style={'display': 'block'}),
            html.Small('Às vezes, as pessoas têm muitas razões para se machucar, além de querer morrer. O que pode ter sido suas razões para auto-mutilação ou suicídio?', style={'display': 'block'}),
            html.Small('Quão graves foram seus ferimentos?', style={'display': 'block'}),
            html.Small('Quais eram seus pensamentos no momento do ato?', style={'display': 'block'}),
            html.Small('O que você acredita ser o resultado de sua automutilação ou tentativa de suicídio?', style={'display': 'block'}),
            html.Small('Você achou que realmente iria morrer?', style={'display': 'block'}),
            html.Small('O que você acha que os outros iriam pensar sobre sua automutilação ou suicídio?', style={'display': 'block'}),
            html.Small('Outras pessoas estavam presentes quando você fez isso?', style={'display': 'block'}),
            html.Small('Como você conseguiu ajuda depois?', style={'display': 'block'}),
            html.Small('Você procurou ajuda por si próprio ou alguém o ajudou?', style={'display': 'block'}),
            html.Small('Você previu que poderia ser descoberto? Se não, como foi descoberto?', style={'display': 'block'}),
            html.Small('Como você se sentiu após sua tentativa?', style={'display': 'block'}),
            html.Small('Você sentiu alívio ou arrependimento por estar vivo?', style={'display': 'block'}),
            html.Small('Você recebeu tratamento após sua tentativa?', style={'display': 'block'}),
            html.Small('Você recebeu tratamento após sua tentativa?', style={'display': 'block'}),
            html.Small('Você foi avaliado em um pronto socorro ou em um serviço de internação/ambulatorial?', style={'display': 'block'}),
            html.Small('Como você pensa e se sente sobre sua vida agora?', style={'display': 'block'}),
            html.Small('As coisas mudaram para você?', style={'display': 'block'}),
            html.Small('Você vê sua vida da mesma forma ou de forma diferente?', style={'display': 'block'}),
            html.Small('Houve outras vezes no passado em que você tentou se machucar (ou se matar)?', style={'display': 'block'}),
            html.Small('Quantas vezes você tentou se machucar, ou tentou tirar sua vida?', style={'display': 'block'}),
            html.Small('Quantas vezes você tentou se machucar, ou tentou tirar sua vida?', style={'display': 'block'}),
            html.P(),
            html.P('Em caso de pensamentos e tentaticas suicidas frequentes:'),
            html.Small('Quais eram seus pensamentos e sentimentos no momento em que você pretendia o suicídio?', style={'display': 'block'}),
            html.Small('Quando foi sua tentativa mais grave de prejudicar ou tirar sua vida?', style={'display': 'block'}),
            html.Small('O que aconteceu pouco antes de você fazer isso, e o que aconteceu depois?', style={'display': 'block'}),
            html.Small('Como você se sente em relação ao seu próprio futuro?', style={'display': 'block'}),
            html.Small('O que o ajudaria a sentir ou pensar de forma mais positiva, otimista e esperançosa sobre o seu futuro?', style={'display': 'block'}),
            html.Small('O que tornaria mais (ou menos) provável que você tentasse tirar a própria vida?', style={'display': 'block'}),
            html.Small('O que acontece em sua vida para fazer você desejar morrer ou fugir da vida?', style={'display': 'block'}),
            html.Small('Se você começasse a ter pensamentos de se machucar ou se matar novamente, o que você faria para evitar eles?', style={'display': 'block'}),
            html.Small('O que você acha que pode ser uma razão para viver?', style={'display': 'block'}),
            html.P(),
        ], title='Conflitos'),
        dbc.AccordionItem([
            html.Small('Descreva seu humor diário típico (normalmente).', style={'display': 'block'}),
            html.Small('Você tem muitas flutuações de humor ao longo do seu dia?', style={'display': 'block'}),
            html.Small('O que te deixa para baixo ou faz você se sentir triste?', style={'display': 'block'}),
            html.Small('O que te deixa feliz e faz você se sentir mais otimista?', style={'display': 'block'}),
            html.Small('Em geral, como você descreveria seu humor?', style={'display': 'block'}),
            html.Small('O que as pessoas próximas a você dizem sobre seu humor? Você fica bravo facilmente?', style={'display': 'block'}),
            html.Small('Como você se livra do mau humor?', style={'display': 'block'}),
            html.Small('Você fica bravo quando não consegue o que quer ou perde o controle?', style={'display': 'block'}),
            html.Small('Como sua raiva se manifesta?', style={'display': 'block'}),
            html.Small('Como você normalmente lida com irritações e frustrações?', style={'display': 'block'}),
            html.Small('O que seria necessário para você se sentir mais feliz ou mais em paz?', style={'display': 'block'}),
            html.Small('Como você acha que o seu humor afeta nos seus relacionamentos?', style={'display': 'block'}),
            html.Small('Seu humor é como uma montanha-russa ou é estável?', style={'display': 'block'}),
            html.Small('Todos nós usamos estratégias diferentes para lidar com isso. Você encontra-se buscando cafeína, drogas, álcool, sexo, compras, a internet ou qualquer outra coisa para fazer você se sentir melhor?', style={'display': 'block'}),
            html.P(),
        ], title='Humor'),
        dbc.AccordionItem([
            html.H6('Com Base em Sofrimento:'),
            html.Small('Qual sentimento você gostaria de eliminar hoje?', style={'display': 'block'}),
            html.Small('O que esses sentimentos estão lhe dizendo?', style={'display': 'block'}),
            html.Small('O que o sentimento sugere que você deveria fazer para ajudar a melhorar as coisas?', style={'display': 'block'}),
            html.Small('Você vai me avisar da próxima vez que sentir emoções tão fortes?', style={'display': 'block'}),
            html.Small('O que o ajudaria a se sentir mais tranquilo?', style={'display': 'block'}),
            html.Small('O que mais você sente que te traz sofrimento?', style={'display': 'block'}),
            html.Small('O que mais você sente?', style={'display': 'block'}),
            html.Small('Consegue identificar em sua rotina algum gatilho para este sentimento?', style={'display': 'block'}),
            html.P(),
        ], title='Sentimentos'),
        dbc.AccordionItem([
            html.H6('Projeções e Metas'),
            html.Small('', style={'display': 'block'}),
            html.Small('O que você gostaria de ver acontecer até o final das nossas sessões?', style={'display': 'block'}),
            html.Small('O que você já tentou e o que foi útil?', style={'display': 'block'}),
            html.Small('Que diferença isso faria/fez em sua vida?', style={'display': 'block'}),
            html.Small('Como você vai se sentir quando isso acontecer? Ou o que você gostaria de estar sentindo?', style={'display': 'block'}),
            html.Small('O que consegue observar que já está dando certo no momento?', style={'display': 'block'}),
            html.Small('Qual é o objetivo mínimo que você gostaria de alcançar?', style={'display': 'block'}),
            html.Small('O que seria diferente em sua vida quando você alcançasse seu objetivo?', style={'display': 'block'}),
            html.Small('Como essa mudança faria a diferença para você?', style={'display': 'block'}),
            html.Small('Como essa mudança faria a diferença para você?', style={'display': 'block'}),
            html.Small('Como você saberá que seu objetivo foi alcançado?', style={'display': 'block'}),
            html.Small('Como você saberá que seu objetivo foi alcançado?', style={'display': 'block'}),
            html.Small('Como eu poderia dizer que seu objetivo foi alcançado?', style={'display': 'block'}),
            html.Small('O que mais será diferente quando você atingir seu objetivo?', style={'display': 'block'}),
            html.Small('O que mais será diferente quando você atingir seu objetivo?', style={'display': 'block'}),
            html.Small('O que mais será diferente quando você atingir seu objetivo?', style={'display': 'block'}),
            html.Small('Qual é o seu objetivo imediato ou a curto prazo na vida?', style={'display': 'block'}),
            html.Small('Quais são os obstáculos em sua vida que o afastam de seus objetivos?', style={'display': 'block'}),
            html.Small('O que você planeja fazer a seguir?', style={'display': 'block'}),
            html.P(),
        ], title='Expectativa de Vida'),
    ])]),
    html.P(),
    html.Div(id = 'saida_consulta_setting_analitico')
])

layout_consulta_evolucao = html.Div([
    html.H6('Selecione um paciente:'),
    dcc.Dropdown(
        id='menu_selecao_paciente',
        options=[{'label': label, 'value': value} for value, label in nomes.items()],
        value=list(nomes.keys())[0] if nomes else None),
    html.P(id='valor_selecionado'),
    html.P(),
    html.P(),
    html.P(),
    html.P(),
    html.Div(id = 'saida_consulta_evolucao')
])

layout_consulta_historico_consultas = html.Div([
    html.H6('Selecione um paciente:'),
    dcc.Dropdown(
        id='menu_selecao_paciente',
        options=[{'label': label, 'value': value} for value, label in nomes.items()],
        value=list(nomes.keys())[0] if nomes else None),
    html.P(id='valor_selecionado'),
    html.P(),
    html.P(),
    html.P(),
    html.P(),
    html.Div(id = 'saida_consulta_historico_consultas')
])

layout_consulta_ferramentas = html.Div([
    html.H6('Selecione um paciente:'),
    dcc.Dropdown(
        id='menu_selecao_paciente',
        options=[{'label': label, 'value': value} for value, label in nomes.items()],
        value=list(nomes.keys())[0] if nomes else None),
    html.P(id='valor_selecionado'),
    html.P(),
    html.P(),
    html.P(),
    html.P(),
    html.Div(id = 'saida_consulta_ferramentas')
])

layout_consulta_laudos_pareceres = html.Div([
    html.H6('Selecione um paciente:'),
    dcc.Dropdown(
        id='menu_selecao_paciente',
        options=[{'label': label, 'value': value} for value, label in nomes.items()],
        value=list(nomes.keys())[0] if nomes else None),
    html.P(id='valor_selecionado'),
    html.P(),
    html.P(),
    html.P(),
    html.P(),
    html.Div(id = 'saida_consulta_laudos_pareceres')
])

layout_consulta_hipotese_diagnostica = html.Div([
    html.H6('Selecione um paciente:'),
    dcc.Dropdown(
        id='menu_selecao_paciente',
        options=[{'label': label, 'value': value} for value, label in nomes.items()],
        value=list(nomes.keys())[0] if nomes else None),
    html.P(id='valor_selecionado'),
    html.P(),
    html.P(),
    html.P(),
    html.P(),
    html.Div(id = 'saida_consulta_hipotese_diagnostica')
])

layout_tec_analise_respostas = html.Div([
    html.Div([dbc.Accordion([
        dbc.AccordionItem([
            html.Small('Resposta franca e direta – Resposta mais positiva e produtiva.', style={'display': 'block'}),
            html.Small('Clara mentira – o cliente pode mentir em resposta a uma pergunta. O terapeuta pode ser capaz de entender uma mentira com base na plausibilidade da resposta mas também na comunicação não verbal que foi utilizada de imediato antes, durante e depois da resposta ser dada.', style={'display': 'block'}),
            html.Small('Fora de contexto – O cliente pode dizer algo totalmente desconectado ou irrelevante para a pergunta ou tentar mudar de assunto. Pode ser apropriado reformular uma pergunta nesses casos.', style={'display': 'block'}),
            html.Small('Resposta parcial – Os clientes podem ser seletivos sobre quais perguntas ou partes de perguntas desejam para responder.', style={'display': 'block'}),
            html.Small('Evitando a resposta – Isso pode ser feito respondendo a uma pergunta com uma pergunta ou tentando desviar atenção para algum aspecto positivo do tópico ou redirecionar para outro tópico.', style={'display': 'block'}),
            html.Small('Stalling – Isso pode ser usado quando um cliente sente que é necessário mais tempo para formular uma resposta.', style={'display': 'block'}),
            html.Small('Distorção – Os clientes podem dar respostas distorcidas a perguntas com base em suas percepções de normas, estereótipos e outras formas de preconceito. Diferente de mentir, os entrevistados podem não perceber sua as respostas são influenciadas por preconceitos ou por sua própria experiência pessoal.', style={'display': 'block'}),
            html.Small('Recusa – O cliente pode simplesmente recusar-se a responder, seja calando-se ou orientando-se a recusar-se a responder.', style={'display': 'block'}),
            html.Small('Defensivo – O cliente pode responder defensivamente a perguntas que o deixam desconfortável.', style={'display': 'block'}),
            html.P(),
        ], title='Análise Geral'),
        dbc.AccordionItem([
            html.Small('A análise de conteúdo é uma técnica amplamente utilizada na análise de respostas em sessões de terapia. Ela envolve a identificação e a codificação de temas e padrões em um conjunto de dados de respostas, geralmente com base em categorias previamente definidas.', style={'display': 'block'}),
            html.Small('Existem várias etapas no processo de análise de conteúdo. A primeira etapa é a preparação dos dados, que envolve a transcrição das respostas dos pacientes em um formato legível. Em seguida, os dados são organizados em unidades de análise, que podem ser frases, parágrafos ou segmentos de conversa.', style={'display': 'block'}),
            html.Small('Na etapa seguinte, os terapeutas definem as categorias a serem usadas na análise. Essas categorias podem ser baseadas em teorias ou modelos específicos, como a teoria cognitivo-comportamental, ou podem ser criadas especificamente para o estudo em questão. As categorias podem ser temáticas, de acordo com o conteúdo da resposta, ou estruturais, de acordo com a forma como a resposta é apresentada.', style={'display': 'block'}),
            html.Small('Uma vez que as categorias são definidas, os dados são codificados. Isso envolve a atribuição de um ou mais códigos a cada unidade de análise, com base na categoria apropriada. Os códigos podem ser quantitativos, como números ou frequências, ou qualitativos, como palavras-chave ou descrições.', style={'display': 'block'}),
            html.Small('Por fim, os dados codificados são analisados para identificar padrões e tendências. Isso pode envolver o cálculo de estatísticas descritivas, como frequências e porcentagens, ou a realização de análises mais avançadas, como análises de cluster ou análises de fatores.', style={'display': 'block'}),
            html.Small('Embora a análise de conteúdo seja uma técnica útil na análise de respostas em sessões de terapia, ela apresenta algumas limitações. Por exemplo, a análise pode ser influenciada pela subjetividade do terapeuta na seleção das categorias e na codificação dos dados. Além disso, a análise de conteúdo pode não capturar nuances e complexidades nas respostas dos pacientes que são importantes para a compreensão do processo terapêutico.', style={'display': 'block'}),
            html.P(),
        ], title='Análise de Conteúdo'),
        dbc.AccordionItem([
            html.Small('A análise de discurso é uma técnica de análise de respostas em sessões de terapia que se concentra na forma como as palavras e a linguagem são usadas para construir significado e sentido. Essa técnica é baseada na ideia de que as palavras não são apenas veículos para a transmissão de informações, mas também desempenham um papel fundamental na construção da realidade e das relações sociais.', style={'display': 'block'}),
            html.Small('Existem várias abordagens teóricas para a análise de discurso, mas todas elas compartilham a ideia de que a linguagem é um instrumento poderoso na criação e na reprodução de poder e dominação. A análise de discurso se concentra na identificação de padrões e temas nas maneiras como as pessoas falam e escrevem, e como esses padrões são usados para sustentar e justificar as relações de poder existentes.', style={'display': 'block'}),
            html.Small('Na análise de discurso, o terapeuta pode analisar as respostas dos pacientes em termos de como as palavras são usadas para construir significado, incluindo a construção de identidades, de relações sociais e de narrativas pessoais. Essa análise pode ser feita em diferentes níveis, incluindo o nível lexical (análise de palavras específicas), o nível gramatical (análise da estrutura e organização da linguagem) e o nível discursivo (análise do uso de metáforas, referências culturais e outras estratégias retóricas).', style={'display': 'block'}),
            html.Small('Ao analisar as respostas dos pacientes, é importante que o terapeuta leve em consideração o contexto social, cultural e histórico em que a terapia está ocorrendo. Isso inclui considerar as diferenças culturais e linguísticas entre o terapeuta e o paciente, bem como as normas sociais e culturais que influenciam a forma como a linguagem é usada.', style={'display': 'block'}),
            html.Small('Embora a análise de discurso seja uma técnica útil para a compreensão da construção social da realidade e das relações de poder, ela também apresenta algumas limitações. Por exemplo, a análise pode ser influenciada pela subjetividade do terapeuta na seleção e interpretação dos dados. Além disso, a análise de discurso pode não capturar aspectos não verbais da comunicação, como a expressão facial e a linguagem corporal.', style={'display': 'block'}),
            html.P(),
        ], title='Análise de Discurso'),
        dbc.AccordionItem([
            html.Small('A análise de sentimento é uma técnica de análise de respostas em sessões de terapia que se concentra na identificação das emoções e dos sentimentos expressos pelo paciente. Essa técnica é baseada na ideia de que as emoções e os sentimentos são uma parte importante da experiência humana e podem ter um impacto significativo na saúde mental e emocional.', style={'display': 'block'}),
            html.Small('Existem várias abordagens teóricas para a análise de sentimento, mas todas elas compartilham a ideia de que as emoções e os sentimentos podem ser identificados por meio do uso de palavras e expressões específicas na linguagem. ', style={'display': 'block'}),
            html.Small('A análise de sentimento se concentra na identificação de palavras e frases que indicam emoções e sentimentos positivos ou negativos, e na classificação dessas palavras em categorias específicas.', style={'display': 'block'}),
            html.Small('Na análise de sentimento, o terapeuta pode analisar as respostas dos pacientes em termos das emoções e dos sentimentos que estão sendo expressos. Essa análise pode ser feita em diferentes níveis, incluindo o nível das palavras (análise de palavras específicas que indicam emoções e sentimentos), o nível do discurso (análise do uso de metáforas, referências culturais e outras estratégias retóricas) e o nível do contexto (análise do contexto social, cultural e histórico em que a terapia está ocorrendo).', style={'display': 'block'}),
            html.Small('Ao analisar as respostas dos pacientes, é importante que o terapeuta leve em consideração o contexto social, cultural e histórico em que a terapia está ocorrendo. Isso inclui considerar as diferenças culturais e linguísticas entre o terapeuta e o paciente, bem como as normas sociais e culturais que influenciam a expressão de emoções e sentimentos.', style={'display': 'block'}),
            html.Small('Embora a análise de sentimento seja uma técnica útil para a compreensão das emoções e dos sentimentos expressos pelos pacientes, ela também apresenta algumas limitações. Por exemplo, a análise pode ser influenciada pela subjetividade do terapeuta na seleção e interpretação dos dados. Além disso, a análise de sentimento pode não capturar aspectos não verbais da comunicação, como a expressão facial e a linguagem corporal.', style={'display': 'block'}),
            html.P(),
        ], title='Análise de Sentimentos'),
        dbc.AccordionItem([
            html.Small('A análise de linguagem corporal é uma técnica de análise de respostas em sessões de terapia que se concentra na observação dos movimentos corporais do paciente. Essa técnica é baseada na ideia de que a linguagem corporal pode fornecer informações importantes sobre o estado emocional e psicológico do paciente.', style={'display': 'block'}),
            html.Small('Existem vários tipos de linguagem corporal que podem ser observados durante uma sessão de terapia, incluindo expressões faciais, postura, gestos, movimentos dos olhos e outros comportamentos não verbais. Cada um desses comportamentos pode indicar diferentes emoções e sentimentos, como ansiedade, tristeza, raiva, medo, alegria e confiança.', style={'display': 'block'}),
            html.Small('Ao observar a linguagem corporal do paciente, o terapeuta pode identificar padrões comportamentais que podem ser úteis para compreender a natureza dos problemas emocionais e psicológicos enfrentados pelo paciente. Por exemplo, um paciente que apresenta uma postura fechada e tensa pode estar expressando sentimentos de ansiedade ou medo, enquanto um paciente que apresenta uma postura aberta e relaxada pode estar expressando sentimentos de confiança e conforto.', style={'display': 'block'}),
            html.Small('A análise de linguagem corporal pode ser particularmente útil quando o paciente tem dificuldade em expressar emoções e sentimentos verbalmente. Nesses casos, a linguagem corporal pode fornecer pistas importantes sobre os pensamentos e emoções do paciente.', style={'display': 'block'}),
            html.Small('No entanto, assim como a análise de sentimento, a análise de linguagem corporal também apresenta algumas limitações. Por exemplo, os movimentos corporais podem ser influenciados por fatores externos, como a cultura, o ambiente e a personalidade do paciente. Além disso, a interpretação da linguagem corporal pode ser subjetiva e requerer habilidades avançadas de observação e análise.', style={'display': 'block'}),
            html.P(),
        ], title='Análise de Linguagem Corporal'),
        dbc.AccordionItem([
            html.Small('A análise de padrões comportamentais é uma técnica de análise de respostas em sessões de terapia que se concentra na identificação de padrões comportamentais repetitivos em pacientes. Esses padrões podem incluir comportamentos disfuncionais, como evitar situações estressantes ou ter pensamentos negativos persistentes.', style={'display': 'block'}),
            html.Small('A identificação de padrões comportamentais pode ser útil para entender a natureza dos problemas emocionais e psicológicos enfrentados pelo paciente, bem como para desenvolver estratégias de tratamento eficazes. Por exemplo, um paciente que apresenta um padrão comportamental de evitar situações estressantes pode se beneficiar de técnicas de exposição gradual e dessensibilização.', style={'display': 'block'}),
            html.Small('A análise de padrões comportamentais também pode ser útil para avaliar o progresso do tratamento ao longo do tempo. Ao monitorar as mudanças nos padrões comportamentais do paciente, o terapeuta pode avaliar se as estratégias de tratamento estão sendo eficazes e fazer ajustes conforme necessário.', style={'display': 'block'}),
            html.Small('No entanto, a análise de padrões comportamentais também apresenta algumas limitações. Por exemplo, os padrões comportamentais podem ser influenciados por fatores externos, como o ambiente e as experiências passadas do paciente. Além disso, a interpretação dos padrões comportamentais pode ser subjetiva e requerer habilidades avançadas de observação e análise.', style={'display': 'block'}),
            html.P(),
        ], title='Análise de Padrões Comportamentais'),
        dbc.AccordionItem([
            html.Small('A análise de mudanças na linguagem e na expressão emocional é outra técnica de análise de respostas em sessões de terapia que pode ser útil para entender os problemas emocionais e psicológicos enfrentados pelos pacientes. Essa técnica se concentra na análise de mudanças na linguagem e na expressão emocional do paciente ao longo do tempo.', style={'display': 'block'}),
            html.Small('Por exemplo, um paciente que inicialmente usa uma linguagem negativa e expressa emoções negativas pode mostrar uma melhoria no tratamento, passando a usar uma linguagem mais positiva e expressando emoções positivas. Essas mudanças na linguagem e na expressão emocional podem indicar uma mudança positiva no estado emocional e psicológico do paciente.', style={'display': 'block'}),
            html.Small('A análise de mudanças na linguagem e na expressão emocional também pode ser útil para identificar as necessidades do paciente e ajustar as estratégias de tratamento de acordo. Por exemplo, se um paciente parece estar lidando com uma emoção específica, como a tristeza, o terapeuta pode ajustar as estratégias de tratamento para se concentrar em lidar com essa emoção.', style={'display': 'block'}),
            html.Small('No entanto, assim como outras técnicas de análise de respostas, a análise de mudanças na linguagem e na expressão emocional apresenta algumas limitações. A interpretação dessas mudanças pode ser subjetiva e requerer habilidades avançadas de observação e análise. Além disso, as mudanças na linguagem e na expressão emocional podem ser influenciadas por fatores externos, como o ambiente e as experiências passadas do paciente.', style={'display': 'block'}),
            html.P(),
        ], title='Análise da Expressão Emocional'),
                dbc.AccordionItem([
            html.Small('A análise de respostas fisiológicas é uma técnica de análise de respostas em sessões de terapia que se concentra na medição das respostas fisiológicas do paciente. Essas respostas incluem, entre outras, a frequência cardíaca, a pressão arterial, a temperatura corporal e a condutância da pele.', style={'display': 'block'}),
            html.Small('Essa técnica pode ser útil para entender as reações físicas do paciente a diferentes estímulos emocionais e psicológicos. Por exemplo, um paciente que apresenta um aumento na frequência cardíaca e na condutância da pele em resposta a um estímulo específico pode estar enfrentando uma emoção intensa, como a ansiedade.', style={'display': 'block'}),
            html.Small('A análise de respostas fisiológicas pode ser realizada por meio de equipamentos como sensores de frequência cardíaca, monitores de pressão arterial e sensores de condutância da pele. Os dados obtidos por esses equipamentos podem ser registrados e analisados para fornecer informações úteis sobre as respostas fisiológicas do paciente.', style={'display': 'block'}),
            html.Small('No entanto, é importante lembrar que a análise de respostas fisiológicas tem algumas limitações. As respostas fisiológicas podem ser influenciadas por fatores externos, como a atividade física e a ingestão de alimentos e bebidas. Além disso, as respostas fisiológicas podem não refletir com precisão o estado emocional e psicológico do paciente.', style={'display': 'block'}),
            html.P(),
        ], title='Análise de Respostas Fisiológicas'),
    ])]),
    html.P(),
])